description: Fake test suite

providers:
  - reverser:whatever

prompts:
  - file:///promptA.txt
  - file:///prompts/*.txt

tests:
  - file:///testA.yaml
  - file:///testB.yaml
  - description: Local ref
    vars:
      word: file:///varA.txt
    assert:
      - description: Contains the word
        type: contains
        vars:
          needle: ereht
