description: Fake test suite

providers:
  - reverser:whatever

prompts:
  - file:///promptA.txt
  - file:///prompts/*.txt
  - =gen: file:///code.ts

tests:
  - file:///testA.yaml
  - file:///tests/**/*.yaml
  - description: Local ref
    vars:
      word: file:///varA.txt
    assert:
      - description: Contains the word
        type: contains
        vars:
          needle: ereht
  - =gen-tests: file:///tests.csv