description: foo

providers:
  - gemini:gemini-1.5-pro-latest
  - gemini:gemini-1.5-flash-latest

prompts:
  - "You only speak about puppies. Respond to the user's request: {{ request }}"
  - >
    [
      { "image": "{{image}}" },
      { "text": "Given this image, respond to the user's request: {{request}}" }
    ]

tests:
  - description: Simple test
    vars:
      image: file:///files/puppy.jpg
      request: Write a haiku
    assert:
      - description: Contains a puppy
        type: icontains
        vars:
          needle: pup
